# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGA_Learning_Journey/Pro/CNN___/project/project_1.srcs/sources_1/ip/eth_dcfifo/eth_dcfifo.xci
# IP: The module: 'eth_dcfifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/project/project_1.srcs/sources_1/ip/eth_dcfifo/eth_dcfifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_dcfifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/project/project_1.srcs/sources_1/ip/eth_dcfifo/eth_dcfifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_dcfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/project/project_1.srcs/sources_1/ip/eth_dcfifo/eth_dcfifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_dcfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/FPGA_Learning_Journey/Pro/CNN___/project/project_1.srcs/sources_1/ip/eth_dcfifo/eth_dcfifo.xci
# IP: The module: 'eth_dcfifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/project/project_1.srcs/sources_1/ip/eth_dcfifo/eth_dcfifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_dcfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/project/project_1.srcs/sources_1/ip/eth_dcfifo/eth_dcfifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_dcfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/project/project_1.srcs/sources_1/ip/eth_dcfifo/eth_dcfifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_dcfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
