# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.cache/wt [current_project]
set_property parent.project_path D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/axi_ddr3_rw/axi_ctrl.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/axi_ddr3_rw/axi_ddr_top.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/axi_ddr3_rw/axi_master_read.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/axi_ddr3_rw/axi_master_write.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/hdmi/encode.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/hdmi/hdmi_ctrl.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/ov5640/i2c_ctrl.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/ov5640/ov5640_cfg.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/ov5640/ov5640_data.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/ov5640/ov5640_top.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/hdmi/par2ser.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/hdmi/top_hdmi.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/hdmi/vga_timing_ctrl.v
  D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/src/ddr3_test.v
}
read_ip -quiet D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/axi_ddr/axi_ddr.xci
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/axi_ddr/axi_ddr/user_design/constraints/axi_ddr.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/axi_ddr/axi_ddr/user_design/constraints/axi_ddr_ooc.xdc]

read_ip -quiet D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/rd_fifo/rd_fifo.xci
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/rd_fifo/rd_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/rd_fifo/rd_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/rd_fifo/rd_fifo_ooc.xdc]

read_ip -quiet D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/wr_fifo/wr_fifo.xci
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/wr_fifo/wr_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/wr_fifo/wr_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/sources_1/ip/wr_fifo/wr_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/constrs_1/new/ddr3.xdc
set_property used_in_implementation false [get_files D:/FPGA_Learning_Journey/Pro/OV5640_DDR3_HDMI___/project/project_1.srcs/constrs_1/new/ddr3.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ddr3_test -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ddr3_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ddr3_test_utilization_synth.rpt -pb ddr3_test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
