set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property PACKAGE_PIN N18 [get_ports sys_clk]
set_property PACKAGE_PIN G19 [get_ports sys_rst_n]
set_property PACKAGE_PIN J18 [get_ports tx]
set_property PACKAGE_PIN G20 [get_ports rx]
