set_property PACKAGE_PIN J18 [get_ports cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports sck]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property PACKAGE_PIN K17 [get_ports sck]
set_property PACKAGE_PIN N18 [get_ports sys_clk]
set_property PACKAGE_PIN L16 [get_ports sys_rst_n]
set_property PACKAGE_PIN F19 [get_ports mosi]
set_property PACKAGE_PIN E19 [get_ports rx]
set_property PACKAGE_PIN F20 [get_ports tx]

