# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/project without ipchecksum/project.cache/wt} [current_project]
set_property parent.project_path {D:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/project without ipchecksum/project.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/project without ipchecksum/project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/src/arp_send_rgmii_crc_with_ipchecksum/checksum.v
  D:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/src/arp_send_rgmii_crc_with_ipchecksum/crc32_d8.v
  D:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/src/arp_send_rgmii_crc_with_ipchecksum/eth_send.v
  D:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/src/arp_send_rgmii_crc_with_ipchecksum/eth_send_test.v
  D:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/src/arp_send_rgmii_crc_with_ipchecksum/gmii_to_rgmii.v
  D:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/src/arp_send_rgmii_crc_with_ipchecksum/eth_send_test_rgmii.v
}
read_ip -quiet {{D:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/project without ipchecksum/project.srcs/sources_1/ip/pll/pll.xci}}
set_property used_in_implementation false [get_files -all {{d:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/project without ipchecksum/project.srcs/sources_1/ip/pll/pll_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/project without ipchecksum/project.srcs/sources_1/ip/pll/pll.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/project without ipchecksum/project.srcs/sources_1/ip/pll/pll_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/project without ipchecksum/project.srcs/constrs_1/new/eth_udp.xdc}}
set_property used_in_implementation false [get_files {{D:/FPGA_Learning_Journey/Pro/ETH_udp_send_rgmii___/project without ipchecksum/project.srcs/constrs_1/new/eth_udp.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top eth_send_test_rgmii -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef eth_send_test_rgmii.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file eth_send_test_rgmii_utilization_synth.rpt -pb eth_send_test_rgmii_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
