set_property IOSTANDARD LVCMOS15 [get_ports sys_clk]
set_property PACKAGE_PIN U7 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS15 [get_ports sys_rst_n]
set_property PACKAGE_PIN R4 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_d]
set_property PACKAGE_PIN U5 [get_ports uart_rx_d]
set_property PACKAGE_PIN T6 [get_ports uart_tx_d]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_d]

set_property IOSTANDARD LVCMOS15 [get_ports {key[0]}]
set_property PACKAGE_PIN T4 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {key[1]}]
set_property PACKAGE_PIN T3 [get_ports {key[1]}]


# set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_n[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_n[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_n[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_n[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_n[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_n[0]}]
# set_property PACKAGE_PIN J15 [get_ports {seg_sel_n[0]}]
# set_property PACKAGE_PIN H17 [get_ports {seg_sel_n[1]}]
# set_property PACKAGE_PIN H13 [get_ports {seg_sel_n[2]}]
# set_property PACKAGE_PIN G17 [get_ports {seg_sel_n[3]}]
# set_property PACKAGE_PIN H18 [get_ports {seg_sel_n[4]}]
# set_property PACKAGE_PIN G18 [get_ports {seg_sel_n[5]}]

set_property PACKAGE_PIN K21 [get_ports {tmds_data_p[1]}]
set_property PACKAGE_PIN J22 [get_ports {tmds_data_p[0]}]
set_property PACKAGE_PIN H20 [get_ports {tmds_data_p[2]}]
set_property PACKAGE_PIN J20 [get_ports tmds_clk_p]
set_property PACKAGE_PIN AA8 [get_ports ddc_scl]
set_property PACKAGE_PIN AB8 [get_ports ddc_sda]
set_property IOSTANDARD LVCMOS15 [get_ports ddc_scl]
set_property IOSTANDARD LVCMOS15 [get_ports ddc_sda]

set_property IOSTANDARD LVCMOS15 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[0]}]
set_property PACKAGE_PIN V9 [get_ports {led[0]}]
set_property PACKAGE_PIN Y8 [get_ports {led[1]}]
set_property PACKAGE_PIN Y7 [get_ports {led[2]}]
set_property PACKAGE_PIN W7 [get_ports {led[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[0]}]
set_property PACKAGE_PIN U17 [get_ports {ov5640_data[7]}]
set_property PACKAGE_PIN W17 [get_ports {ov5640_data[6]}]
set_property PACKAGE_PIN V17 [get_ports {ov5640_data[5]}]
set_property PACKAGE_PIN P16 [get_ports {ov5640_data[4]}]
set_property PACKAGE_PIN R17 [get_ports {ov5640_data[3]}]
set_property PACKAGE_PIN R16 [get_ports {ov5640_data[2]}]
set_property PACKAGE_PIN P15 [get_ports {ov5640_data[1]}]
set_property PACKAGE_PIN P17 [get_ports {ov5640_data[0]}]
set_property PACKAGE_PIN N14 [get_ports ov5640_href]
set_property PACKAGE_PIN U18 [get_ports ov5640_pclk]
set_property PACKAGE_PIN AB18 [get_ports ov5640_pwdn]
set_property PACKAGE_PIN N17 [get_ports ov5640_rst_n]
set_property PACKAGE_PIN P14 [get_ports ov5640_vsync]
set_property PACKAGE_PIN N13 [get_ports sccb_scl]
set_property PACKAGE_PIN R14 [get_ports sccb_sda]
set_property IOSTANDARD LVCMOS33 [get_ports sccb_sda]
set_property IOSTANDARD LVCMOS33 [get_ports sccb_scl]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_href]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov5640_pclk_IBUF]


set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_n[0]}]

set_property PACKAGE_PIN W19 [get_ports rgmii_tx_clk]
set_property PACKAGE_PIN N20 [get_ports phy_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n]
set_property PACKAGE_PIN P20 [get_ports {rgmii_tx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_tx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_tx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_tx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_tx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[0]}]
set_property PACKAGE_PIN T20 [get_ports {rgmii_tx_data[2]}]
set_property PACKAGE_PIN W21 [get_ports {rgmii_tx_data[1]}]
set_property PACKAGE_PIN W22 [get_ports {rgmii_tx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_clk]
set_property PACKAGE_PIN W20 [get_ports rgmii_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_en]


