set_property PACKAGE_PIN AB21 [get_ports {rgmii_tx_data[0]}]
set_property PACKAGE_PIN AA20 [get_ports {rgmii_tx_data[1]}]
set_property PACKAGE_PIN AB20 [get_ports {rgmii_tx_data[2]}]
set_property PACKAGE_PIN AA19 [get_ports {rgmii_tx_data[3]}]
set_property PACKAGE_PIN R4 [get_ports clk]
set_property PACKAGE_PIN T21 [get_ports phy_rst_n]
set_property PACKAGE_PIN AA21 [get_ports rgmii_tx_clk]
set_property PACKAGE_PIN AB22 [get_ports rgmii_tx_en]
set_property PACKAGE_PIN U2 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_tx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_tx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_tx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_tx_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[0]}]
set_property PACKAGE_PIN F13 [get_ports {ov5640_data[7]}]
set_property PACKAGE_PIN E13 [get_ports {ov5640_data[6]}]
set_property PACKAGE_PIN E14 [get_ports {ov5640_data[5]}]
set_property PACKAGE_PIN D14 [get_ports {ov5640_data[4]}]
set_property PACKAGE_PIN D15 [get_ports {ov5640_data[3]}]
set_property PACKAGE_PIN C13 [get_ports {ov5640_data[2]}]
set_property PACKAGE_PIN B13 [get_ports {ov5640_data[1]}]
set_property PACKAGE_PIN C14 [get_ports {ov5640_data[0]}]
set_property PACKAGE_PIN B15 [get_ports ov5640_href]
set_property PACKAGE_PIN F14 [get_ports ov5640_pclk]
set_property PACKAGE_PIN F16 [get_ports ov5640_pwdn]
set_property PACKAGE_PIN C15 [get_ports ov5640_rst_n]
set_property PACKAGE_PIN E16 [get_ports ov5640_vsync]
set_property PACKAGE_PIN D16 [get_ports sccb_scl]
set_property PACKAGE_PIN B16 [get_ports sccb_sda]
set_property IOSTANDARD LVCMOS33 [get_ports sccb_sda]
set_property IOSTANDARD LVCMOS33 [get_ports sccb_scl]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_href]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov5640_pclk_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN R2 [get_ports {led[1]}]
set_property PACKAGE_PIN R3 [get_ports {led[0]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list ov5640_pclk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {h_pix_cnt[0]} {h_pix_cnt[1]} {h_pix_cnt[2]} {h_pix_cnt[3]} {h_pix_cnt[4]} {h_pix_cnt[5]} {h_pix_cnt[6]} {h_pix_cnt[7]} {h_pix_cnt[8]} {h_pix_cnt[9]} {h_pix_cnt[10]} {h_pix_cnt[11]} {h_pix_cnt[12]} {h_pix_cnt[13]} {h_pix_cnt[14]} {h_pix_cnt[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {h_cnt[0]} {h_cnt[1]} {h_cnt[2]} {h_cnt[3]} {h_cnt[4]} {h_cnt[5]} {h_cnt[6]} {h_cnt[7]} {h_cnt[8]} {h_cnt[9]} {h_cnt[10]} {h_cnt[11]} {h_cnt[12]} {h_cnt[13]} {h_cnt[14]} {h_cnt[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {h_wr_data[0]} {h_wr_data[1]} {h_wr_data[2]} {h_wr_data[3]} {h_wr_data[4]} {h_wr_data[5]} {h_wr_data[6]} {h_wr_data[7]} {h_wr_data[8]} {h_wr_data[9]} {h_wr_data[10]} {h_wr_data[11]} {h_wr_data[12]} {h_wr_data[13]} {h_wr_data[14]} {h_wr_data[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {ov5640_data_out[0]} {ov5640_data_out[1]} {ov5640_data_out[2]} {ov5640_data_out[3]} {ov5640_data_out[4]} {ov5640_data_out[5]} {ov5640_data_out[6]} {ov5640_data_out[7]} {ov5640_data_out[8]} {ov5640_data_out[9]} {ov5640_data_out[10]} {ov5640_data_out[11]} {ov5640_data_out[12]} {ov5640_data_out[13]} {ov5640_data_out[14]} {ov5640_data_out[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list h_wr_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list ov5640_href_reg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list ov5640_href_rise]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list ov5640_wr_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list p_1_in]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list p_2_in]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list pll/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 8 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {eth_udp_send_inst/payload_dat_i[0]} {eth_udp_send_inst/payload_dat_i[1]} {eth_udp_send_inst/payload_dat_i[2]} {eth_udp_send_inst/payload_dat_i[3]} {eth_udp_send_inst/payload_dat_i[4]} {eth_udp_send_inst/payload_dat_i[5]} {eth_udp_send_inst/payload_dat_i[6]} {eth_udp_send_inst/payload_dat_i[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 14 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {eth_udp_send_inst/rd_data_count[0]} {eth_udp_send_inst/rd_data_count[1]} {eth_udp_send_inst/rd_data_count[2]} {eth_udp_send_inst/rd_data_count[3]} {eth_udp_send_inst/rd_data_count[4]} {eth_udp_send_inst/rd_data_count[5]} {eth_udp_send_inst/rd_data_count[6]} {eth_udp_send_inst/rd_data_count[7]} {eth_udp_send_inst/rd_data_count[8]} {eth_udp_send_inst/rd_data_count[9]} {eth_udp_send_inst/rd_data_count[10]} {eth_udp_send_inst/rd_data_count[11]} {eth_udp_send_inst/rd_data_count[12]} {eth_udp_send_inst/rd_data_count[13]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list eth_udp_send_inst/payload_req_o]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list eth_udp_send_inst/sending_flag]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list eth_udp_send_inst/tx_done]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list eth_udp_send_inst/tx_en_pulse]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_125m]
