set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN U2 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property PACKAGE_PIN R4 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_d]
set_property PACKAGE_PIN U5 [get_ports uart_rx_d]
set_property PACKAGE_PIN T6 [get_ports uart_tx_d]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_d]

set_property PACKAGE_PIN A15 [get_ports {tmds_data_p[1]}]
set_property PACKAGE_PIN A18 [get_ports {tmds_data_p[0]}]
set_property PACKAGE_PIN A13 [get_ports {tmds_data_p[2]}]
set_property PACKAGE_PIN B17 [get_ports tmds_clk_p]
set_property PACKAGE_PIN C17 [get_ports ddc_scl]
set_property PACKAGE_PIN D20 [get_ports ddc_sda]
set_property IOSTANDARD LVCMOS33 [get_ports ddc_scl]
set_property IOSTANDARD LVCMOS33 [get_ports ddc_sda]

set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN R2 [get_ports {led[0]}]
set_property PACKAGE_PIN R3 [get_ports {led[1]}]
set_property PACKAGE_PIN V2 [get_ports {led[2]}]
set_property PACKAGE_PIN Y2 [get_ports {led[3]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_inst/inst/clk_50m]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 24 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ddr_data_inst/byte4_tx_cnt[0]} {ddr_data_inst/byte4_tx_cnt[1]} {ddr_data_inst/byte4_tx_cnt[2]} {ddr_data_inst/byte4_tx_cnt[3]} {ddr_data_inst/byte4_tx_cnt[4]} {ddr_data_inst/byte4_tx_cnt[5]} {ddr_data_inst/byte4_tx_cnt[6]} {ddr_data_inst/byte4_tx_cnt[7]} {ddr_data_inst/byte4_tx_cnt[8]} {ddr_data_inst/byte4_tx_cnt[9]} {ddr_data_inst/byte4_tx_cnt[10]} {ddr_data_inst/byte4_tx_cnt[11]} {ddr_data_inst/byte4_tx_cnt[12]} {ddr_data_inst/byte4_tx_cnt[13]} {ddr_data_inst/byte4_tx_cnt[14]} {ddr_data_inst/byte4_tx_cnt[15]} {ddr_data_inst/byte4_tx_cnt[16]} {ddr_data_inst/byte4_tx_cnt[17]} {ddr_data_inst/byte4_tx_cnt[18]} {ddr_data_inst/byte4_tx_cnt[19]} {ddr_data_inst/byte4_tx_cnt[20]} {ddr_data_inst/byte4_tx_cnt[21]} {ddr_data_inst/byte4_tx_cnt[22]} {ddr_data_inst/byte4_tx_cnt[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 24 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {ddr_data_inst/byte_rx_cnt[0]} {ddr_data_inst/byte_rx_cnt[1]} {ddr_data_inst/byte_rx_cnt[2]} {ddr_data_inst/byte_rx_cnt[3]} {ddr_data_inst/byte_rx_cnt[4]} {ddr_data_inst/byte_rx_cnt[5]} {ddr_data_inst/byte_rx_cnt[6]} {ddr_data_inst/byte_rx_cnt[7]} {ddr_data_inst/byte_rx_cnt[8]} {ddr_data_inst/byte_rx_cnt[9]} {ddr_data_inst/byte_rx_cnt[10]} {ddr_data_inst/byte_rx_cnt[11]} {ddr_data_inst/byte_rx_cnt[12]} {ddr_data_inst/byte_rx_cnt[13]} {ddr_data_inst/byte_rx_cnt[14]} {ddr_data_inst/byte_rx_cnt[15]} {ddr_data_inst/byte_rx_cnt[16]} {ddr_data_inst/byte_rx_cnt[17]} {ddr_data_inst/byte_rx_cnt[18]} {ddr_data_inst/byte_rx_cnt[19]} {ddr_data_inst/byte_rx_cnt[20]} {ddr_data_inst/byte_rx_cnt[21]} {ddr_data_inst/byte_rx_cnt[22]} {ddr_data_inst/byte_rx_cnt[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {ddr_data_inst/uart_rx_data[0]} {ddr_data_inst/uart_rx_data[1]} {ddr_data_inst/uart_rx_data[2]} {ddr_data_inst/uart_rx_data[3]} {ddr_data_inst/uart_rx_data[4]} {ddr_data_inst/uart_rx_data[5]} {ddr_data_inst/uart_rx_data[6]} {ddr_data_inst/uart_rx_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {wr_data[0]} {wr_data[1]} {wr_data[2]} {wr_data[3]} {wr_data[4]} {wr_data[5]} {wr_data[6]} {wr_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list read_enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list ddr_data_inst/uart_rx_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list ddr_data_inst/uart_tx_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list wr_en]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_wiz_inst/inst/clk_25m]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 32 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {rd_data[0]} {rd_data[1]} {rd_data[2]} {rd_data[3]} {rd_data[4]} {rd_data[5]} {rd_data[6]} {rd_data[7]} {rd_data[8]} {rd_data[9]} {rd_data[10]} {rd_data[11]} {rd_data[12]} {rd_data[13]} {rd_data[14]} {rd_data[15]} {rd_data[16]} {rd_data[17]} {rd_data[18]} {rd_data[19]} {rd_data[20]} {rd_data[21]} {rd_data[22]} {rd_data[23]} {rd_data[24]} {rd_data[25]} {rd_data[26]} {rd_data[27]} {rd_data[28]} {rd_data[29]} {rd_data[30]} {rd_data[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list data_rd_valid]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list pix_data_req]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list rd_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_25m]
