# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CNN/OV5640_DDR3_HDMI_UDP_gray___/project/project_1.srcs/sources_1/ip/uint32_to_float/uint32_to_float.xci
# IP: The module: 'uint32_to_float' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CNN/OV5640_DDR3_HDMI_UDP_gray___/project/project_1.srcs/sources_1/ip/uint32_to_float/uint32_to_float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uint32_to_float'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/CNN/OV5640_DDR3_HDMI_UDP_gray___/project/project_1.srcs/sources_1/ip/uint32_to_float/uint32_to_float.xci
# IP: The module: 'uint32_to_float' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CNN/OV5640_DDR3_HDMI_UDP_gray___/project/project_1.srcs/sources_1/ip/uint32_to_float/uint32_to_float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uint32_to_float'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
