# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGA_Learning_Journey/Pro/CNN___/src/ip/exp/exp.xci
# IP: The module: 'exp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/src/ip/exp/exp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'exp'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/FPGA_Learning_Journey/Pro/CNN___/src/ip/exp/exp.xci
# IP: The module: 'exp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/src/ip/exp/exp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'exp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
