set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN U2 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property PACKAGE_PIN R4 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_d]
set_property PACKAGE_PIN U5 [get_ports uart_rx_d]
set_property PACKAGE_PIN T6 [get_ports uart_tx_d]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_d]

set_property PACKAGE_PIN A15 [get_ports {tmds_data_p[1]}]
set_property PACKAGE_PIN A18 [get_ports {tmds_data_p[0]}]
set_property PACKAGE_PIN A13 [get_ports {tmds_data_p[2]}]
set_property PACKAGE_PIN B17 [get_ports tmds_clk_p]
set_property PACKAGE_PIN C17 [get_ports ddc_scl]
set_property PACKAGE_PIN D20 [get_ports ddc_sda]
set_property IOSTANDARD LVCMOS33 [get_ports ddc_scl]
set_property IOSTANDARD LVCMOS33 [get_ports ddc_sda]

set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN R2 [get_ports {led[0]}]
set_property PACKAGE_PIN R3 [get_ports {led[1]}]
set_property PACKAGE_PIN V2 [get_ports {led[2]}]
set_property PACKAGE_PIN Y2 [get_ports {led[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[0]}]
set_property PACKAGE_PIN F13 [get_ports {ov5640_data[7]}]
set_property PACKAGE_PIN E13 [get_ports {ov5640_data[6]}]
set_property PACKAGE_PIN E14 [get_ports {ov5640_data[5]}]
set_property PACKAGE_PIN D14 [get_ports {ov5640_data[4]}]
set_property PACKAGE_PIN D15 [get_ports {ov5640_data[3]}]
set_property PACKAGE_PIN C13 [get_ports {ov5640_data[2]}]
set_property PACKAGE_PIN B13 [get_ports {ov5640_data[1]}]
set_property PACKAGE_PIN C14 [get_ports {ov5640_data[0]}]
set_property PACKAGE_PIN B15 [get_ports ov5640_href]
set_property PACKAGE_PIN F14 [get_ports ov5640_pclk]
set_property PACKAGE_PIN F16 [get_ports ov5640_pwdn]
set_property PACKAGE_PIN C15 [get_ports ov5640_rst_n]
set_property PACKAGE_PIN E16 [get_ports ov5640_vsync]
set_property PACKAGE_PIN D16 [get_ports sccb_scl]
set_property PACKAGE_PIN B16 [get_ports sccb_sda]
set_property IOSTANDARD LVCMOS33 [get_ports sccb_sda]
set_property IOSTANDARD LVCMOS33 [get_ports sccb_scl]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_href]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov5640_pclk_IBUF]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list ov5640_pclk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ov5640_data_out[0]} {ov5640_data_out[1]} {ov5640_data_out[2]} {ov5640_data_out[3]} {ov5640_data_out[4]} {ov5640_data_out[5]} {ov5640_data_out[6]} {ov5640_data_out[7]} {ov5640_data_out[8]} {ov5640_data_out[9]} {ov5640_data_out[10]} {ov5640_data_out[11]} {ov5640_data_out[12]} {ov5640_data_out[13]} {ov5640_data_out[14]} {ov5640_data_out[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list ov5640_wr_en]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_wiz_inst/inst/clk_25m]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 16 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {rd_data[0]} {rd_data[1]} {rd_data[2]} {rd_data[3]} {rd_data[4]} {rd_data[5]} {rd_data[6]} {rd_data[7]} {rd_data[8]} {rd_data[9]} {rd_data[10]} {rd_data[11]} {rd_data[12]} {rd_data[13]} {rd_data[14]} {rd_data[15]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list pix_data_req]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list ov5640_top_inst/cfg_clk_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 1 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list cfg_done]]
create_debug_core u_ila_3 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_3]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_3]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_3]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_3]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_3]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_3]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_3]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_3]
set_property port_width 1 [get_debug_ports u_ila_3/clk]
connect_debug_port u_ila_3/clk [get_nets [list ddr_rw_inst/u_axi_ddr/u_axi_ddr_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe0]
set_property port_width 1 [get_debug_ports u_ila_3/probe0]
connect_debug_port u_ila_3/probe0 [get_nets [list rd_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_3_gen_mmcm.mmcm_i_0]
