# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ddr3.xdc

# IP: ip/eth_dcfifo/eth_dcfifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth_dcfifo || ORIG_REF_NAME==eth_dcfifo} -quiet] -quiet

# IP: ip/rd_fifo/rd_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rd_fifo || ORIG_REF_NAME==rd_fifo} -quiet] -quiet

# IP: ip/wr_fifo/wr_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wr_fifo || ORIG_REF_NAME==wr_fifo} -quiet] -quiet
