# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CNN/OV5640_DDR3_HDMI_UDP_gray___/project/project_1.srcs/sources_1/ip/float_to_q6_10/float_to_q6_10.xci
# IP: The module: 'float_to_q6_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CNN/OV5640_DDR3_HDMI_UDP_gray___/project/project_1.srcs/sources_1/ip/float_to_q6_10/float_to_q6_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_to_q6_10'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/CNN/OV5640_DDR3_HDMI_UDP_gray___/project/project_1.srcs/sources_1/ip/float_to_q6_10/float_to_q6_10.xci
# IP: The module: 'float_to_q6_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CNN/OV5640_DDR3_HDMI_UDP_gray___/project/project_1.srcs/sources_1/ip/float_to_q6_10/float_to_q6_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_to_q6_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
