# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGA_Learning_Journey/Pro/CNN___/src/ip/float_div/float_div.xci
# IP: The module: 'float_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/src/ip/float_div/float_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_div'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/FPGA_Learning_Journey/Pro/CNN___/src/ip/float_div/float_div.xci
# IP: The module: 'float_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/src/ip/float_div/float_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
