# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGA_Learning_Journey/Pro/CNN___/src/ip/mac_res_fifo/mac_res_fifo.xci
# IP: The module: 'mac_res_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/src/ip/mac_res_fifo/mac_res_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_res_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/src/ip/mac_res_fifo/mac_res_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_res_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/FPGA_Learning_Journey/Pro/CNN___/src/ip/mac_res_fifo/mac_res_fifo.xci
# IP: The module: 'mac_res_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/src/ip/mac_res_fifo/mac_res_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_res_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA_Learning_Journey/Pro/CNN___/src/ip/mac_res_fifo/mac_res_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_res_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
