set_property IOSTANDARD LVCMOS33 [get_ports cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports key_in]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports sck]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property PACKAGE_PIN N18 [get_ports sys_clk]
set_property PACKAGE_PIN L16 [get_ports sys_rst_n]
set_property PACKAGE_PIN G19 [get_ports key_in]
set_property PACKAGE_PIN J18 [get_ports cs_n]
set_property PACKAGE_PIN F19 [get_ports mosi]
set_property PACKAGE_PIN K17 [get_ports sck]

