# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/CNN/OV5640_DDR3_HDMI_UDP_gray___/src/ip/fcnn_fifo/fcnn_fifo.xci
# IP: The module: 'fcnn_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CNN/OV5640_DDR3_HDMI_UDP_gray___/src/ip/fcnn_fifo/fcnn_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fcnn_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CNN/OV5640_DDR3_HDMI_UDP_gray___/src/ip/fcnn_fifo/fcnn_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fcnn_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/CNN/OV5640_DDR3_HDMI_UDP_gray___/src/ip/fcnn_fifo/fcnn_fifo.xci
# IP: The module: 'fcnn_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CNN/OV5640_DDR3_HDMI_UDP_gray___/src/ip/fcnn_fifo/fcnn_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fcnn_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CNN/OV5640_DDR3_HDMI_UDP_gray___/src/ip/fcnn_fifo/fcnn_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fcnn_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
