# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param synth.incrementalSynthesisCache D:/FPGA_Learning_Journey/Pro/SobelEdge____/project/.Xil/Vivado-2312-DESKTOP-I8GGJRG/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA_Learning_Journey/Pro/SobelEdge____/project/project.cache/wt [current_project]
set_property parent.project_path D:/FPGA_Learning_Journey/Pro/SobelEdge____/project/project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/FPGA_Learning_Journey/Pro/SobelEdge____/project/project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/FPGA_Learning_Journey/Pro/SobelEdge____/bram_init.coe
read_verilog -library xil_defaultlib {
  D:/FPGA_Learning_Journey/Pro/SobelEdge____/src/encode.v
  D:/FPGA_Learning_Journey/Pro/SobelEdge____/src/hdmi_ctrl.v
  D:/FPGA_Learning_Journey/Pro/SobelEdge____/src/hdmi_rom.v
  D:/FPGA_Learning_Journey/Pro/SobelEdge____/src/par2ser.v
  D:/FPGA_Learning_Journey/Pro/SobelEdge____/src/sobel_ctrl.v
  D:/FPGA_Learning_Journey/Pro/SobelEdge____/src/uart_rx.v
  D:/FPGA_Learning_Journey/Pro/SobelEdge____/src/uart_tx.v
  D:/FPGA_Learning_Journey/Pro/SobelEdge____/src/vga_image_gen.v
  D:/FPGA_Learning_Journey/Pro/SobelEdge____/src/vga_timing_ctrl.v
  D:/FPGA_Learning_Journey/Pro/SobelEdge____/src/sobel.v
}
read_ip -quiet D:/FPGA_Learning_Journey/Pro/SobelEdge____/project/project.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/SobelEdge____/project/project.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/SobelEdge____/project/project.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet D:/FPGA_Learning_Journey/Pro/SobelEdge____/project/project.srcs/sources_1/ip/clk_gen/clk_gen.xci
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/SobelEdge____/project/project.srcs/sources_1/ip/clk_gen/clk_gen_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/SobelEdge____/project/project.srcs/sources_1/ip/clk_gen/clk_gen.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/SobelEdge____/project/project.srcs/sources_1/ip/clk_gen/clk_gen_ooc.xdc]

read_ip -quiet D:/FPGA_Learning_Journey/Pro/SobelEdge____/project/project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA_Learning_Journey/Pro/SobelEdge____/project/project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGA_Learning_Journey/Pro/SobelEdge____/src/hdmi.xdc
set_property used_in_implementation false [get_files D:/FPGA_Learning_Journey/Pro/SobelEdge____/src/hdmi.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top sobel -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sobel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sobel_utilization_synth.rpt -pb sobel_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
